# Generated by Django 4.2.7 on 2023-12-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_uploadedfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='file_size',
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV'), ('txt', 'Text')], max_length=3),
        ),
    ]
