# Generated by Django 4.2.7 on 2023-12-05 15:56

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_uploadedfile_file_name_uploadedfile_file_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to=accounts.models.get_upload_path),
        ),
    ]
